---
interface_loopback:
  - name: Loopback0
    ip: 3.3.3.3
    mask: 255.255.255.255
    desc: OSPF Router ID
  # - name: Loopback1
  #   ip: 3.3.3.33
  #   mask: 255.255.255.255
  #   desc: OSPF Router ID

interface_GigabitEthernet:
  - name: GigabitEthernet0/2
    ip: 10.1.12.2
    mask: 255.255.255.252
    desc: "To_R1_GigabitEthernet0/2"
    
  - name: GigabitEthernet0/3
    ip: 10.1.23.2
    mask: 255.255.255.252
    desc: "To_R2_GigabitEthernet0/3"
