---
- name: NTC Template Parser Demo
  hosts: R3
  gather_facts: false
  tasks:
    - name: Version parser with NTC Template
      ansible.utils.cli_parse:
        command: show version
        parser:
          name: ansible.netcommon.ntc_templates
        set_fact: sh_ver
      register: show_ver_parser

    - name: Print show version
      ansible.builtin.debug:
        msg: 
          - "{{ sh_ver }}"

    # - name: Interface parser with NTC Template
    #   ansible.utils.cli_parse:
    #     command: show ip interface brief
    #     parser:
    #       name: ansible.netcommon.ntc_templates
    #     set_fact: sh_ip

    # - name: Print show version
    #   ansible.builtin.debug:
    #     msg: 
    #       - "{{ sh_ip }}"
